-- AI Control Plane Audit Logs Queries
-- Run these in Snowflake to view audit trail

-- 1. View all audit logs (most recent first)
SELECT 
    ID,
    TIMESTAMP,
    USER_INPUT,
    ACTION,
    TABLE_NAME,
    RECORD_ID,
    SUBSTR(LOGS, 1, 100) || '...' AS LOGS_PREVIEW
FROM MY_DATABASE.PUBLIC.AUDIT_LOGS 
ORDER BY TIMESTAMP DESC 
LIMIT 20;

-- 2. View detailed logs for a specific entry
SELECT 
    ID,
    TIMESTAMP,
    USER_INPUT,
    ACTION,
    TABLE_NAME,
    RECORD_ID,
    LOGS
FROM MY_DATABASE.PUBLIC.AUDIT_LOGS 
WHERE ID = 1  -- Change to specific ID
ORDER BY TIMESTAMP DESC;

-- 3. Summary by action type
SELECT 
    ACTION,
    COUNT(*) AS EXECUTION_COUNT,
    MIN(TIMESTAMP) AS FIRST_EXECUTION,
    MAX(TIMESTAMP) AS LAST_EXECUTION
FROM MY_DATABASE.PUBLIC.AUDIT_LOGS 
GROUP BY ACTION
ORDER BY EXECUTION_COUNT DESC;

-- 4. View logs from today only
SELECT 
    ID,
    TIMESTAMP,
    USER_INPUT,
    ACTION,
    TABLE_NAME,
    JSON_EXTRACT_PATH_TEXT(LOGS, 'status') AS STATUS,
    JSON_EXTRACT_PATH_TEXT(LOGS, 'total_time') AS EXECUTION_TIME_SEC
FROM MY_DATABASE.PUBLIC.AUDIT_LOGS 
WHERE DATE(TIMESTAMP) = CURRENT_DATE()
ORDER BY TIMESTAMP DESC;

-- 5. View failed executions
SELECT 
    ID,
    TIMESTAMP,
    USER_INPUT,
    ACTION,
    JSON_EXTRACT_PATH_TEXT(LOGS, 'status') AS STATUS,
    JSON_EXTRACT_PATH_TEXT(LOGS, 'error') AS ERROR_MESSAGE
FROM MY_DATABASE.PUBLIC.AUDIT_LOGS 
WHERE JSON_EXTRACT_PATH_TEXT(LOGS, 'status') IN ('error', 'cancelled', 'low_confidence')
ORDER BY TIMESTAMP DESC;

-- 6. Performance analysis
SELECT 
    ACTION,
    AVG(CAST(JSON_EXTRACT_PATH_TEXT(LOGS, 'total_time') AS FLOAT)) AS AVG_EXECUTION_TIME,
    MIN(CAST(JSON_EXTRACT_PATH_TEXT(LOGS, 'total_time') AS FLOAT)) AS MIN_EXECUTION_TIME,
    MAX(CAST(JSON_EXTRACT_PATH_TEXT(LOGS, 'total_time') AS FLOAT)) AS MAX_EXECUTION_TIME,
    COUNT(*) AS EXECUTION_COUNT
FROM MY_DATABASE.PUBLIC.AUDIT_LOGS 
WHERE JSON_EXTRACT_PATH_TEXT(LOGS, 'total_time') IS NOT NULL
GROUP BY ACTION
ORDER BY AVG_EXECUTION_TIME DESC;